name: Edit Post

on:
  issues:
    types: [edited]

jobs:
  create-post:
    runs-on: ubuntu-latest

    if: github.event.label.name == 'post'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Create issue as Markdown file
        run: |
          mkdir -p posts
          chmod +x  ../scripts/create_post.sh
          ../scripts/create_post.sh
        shell: bash

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Add issue #${{ github.event.issue.number }} as Markdown file"
          branch: main
          file_pattern: issues/*

