name: Issue to Markdown

on:
  issues:
    types: [opened]

jobs:
  issue_to_md:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Create issue as Markdown file
      run: |
        mkdir -p issues
        echo "# ${{ github.event.issue.title }}" > issues/issue-${{ github.event.issue.number }}.md
        echo "" >> issues/issue-${{ github.event.issue.number }}.md
        echo "## Descrição" >> issues/issue-${{ github.event.issue.number }}.md
        echo "${{ github.event.issue.body }}" >> issues/issue-${{ github.event.issue.number }}.md
        echo "" >> issues/issue-${{ github.event.issue.number }}.md
        echo "## Autor: ${{ github.event.issue.user.login }}" >> issues/issue-${{ github.event.issue.number }}.md
        echo "Issue URL: [${{ github.event.issue.html_url }}](${{ github.event.issue.html_url }})" >> issues/issue-${{ github.event.issue.number }}.md

    - name: Push changes
      uses: ad-m/github-push-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        force: true
